version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2023-10-16T04-13-43Z
    hostname: 'vr-s3'
    container_name: 'vr-minio'
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioAdmin
      MINIO_ROOT_PASSWORD: minioPassword
      MINIO_BROWSER: 'on'
    command: server --console-address ":9001" data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  video-recognition:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: localhost
      S3_ACCESS_KEY_ID: minioAdmin
      S3_SECRET_ACCESS_KEY: minioPassword
      S3_ENDPOINT_URL: http://vr-s3:9000
      VIDEO_S3_BUCKET: video-recognition
      VIDEO_S3_KEY: video.mp4
    volumes:
      - './src:/tmp/video_recognition/src'

volumes:
    minio_data:
