version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2023-10-16T04-13-43Z
    hostname: 'var-s3'
    container_name: 'var-minio'
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioAdmin
      MINIO_ROOT_PASSWORD: minioPassword
      MINIO_BROWSER: 'on'
    command: server --console-address ":9001" data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  video-action-recognizer:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'var-app'
    environment:
      ENV: localhost
      S3_ACCESS_KEY_ID: minioAdmin
      S3_SECRET_ACCESS_KEY: minioPassword
      S3_ENDPOINT_URL: http://var-s3:9000
      S3_REGION: eu-west-1
      INPUT_VIDEO_S3_BUCKET: video-action-recognizer
      INPUT_VIDEO_S3_KEY: videos/video.mp4
      OUTPUT_VIDEO_S3_BUCKET: video-action-recognizer
    volumes:
      - './src:/tmp/video-action-recognizer/src'

volumes:
    minio_data:
